name: avtorepair
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_map: ^5.0.0
  latlong2:
  http: ^1.1.0
  sqflite: ^2.3.0
  shared_preferences:
  jwt_decoder:
  yandex_mapkit: ^3.3.3
  geolocator: ^10.1.0
  equatable: ^2.0.5
  permission_handler: ^11.0.1
  carousel_slider: ^4.2.1
  image_picker: ^1.0.0
  fl_chart: ^0.55.0

  table_calendar: ^3.1.1
  intl: ^0.19.0
  collection: ^1.17.1
  galleryimage: ^2.0.1
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  # uri_to_file:
  image_gallery_saver: ^2.0.3

  path_provider: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/temp/
    - assets/svg/
    

  fonts:
  - family: Urbanist
    fonts:
      - asset: assets/fonts/Urbanist-Light.ttf
        weight: 300
      - asset: assets/fonts/Urbanist-Regular.ttf
      - asset: assets/fonts/Urbanist-Medium.ttf
        weight: 500
      - asset: assets/fonts/Urbanist-Semibold.ttf
        weight: 600
      - asset: assets/fonts/Urbanist-Bold.ttf
        weight: 700
      - asset: assets/fonts/Urbanist-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Urbanist-Black.ttf
        weight: 900
      
